import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';
import { getWibMonthRangeUtc } from '@/lib/wib';

export const dynamic = 'force-dynamic';

export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const monthRange = getWibMonthRangeUtc(searchParams.get('month'))
    if (!monthRange) return NextResponse.json({ error: 'month tidak valid' }, { status: 400 })
    const kebunIdParam = searchParams.get('kebunId');
    const kendaraanPlatParam = searchParams.get('kendaraanPlatNomor');
    const kebunId = kebunIdParam ? Number(kebunIdParam) : null;
    
    let vehiclePlats: string[] | null = null;
    if (kebunId) {
      const notaPlats = await prisma.notaSawit.findMany({
        where: {
          kebunId,
          createdAt: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc },
          kendaraanPlatNomor: { not: null },
        },
        select: { kendaraanPlatNomor: true },
      });
      vehiclePlats = Array.from(new Set(notaPlats.map(n => n.kendaraanPlatNomor!).filter(Boolean)));
    }

    if (kendaraanPlatParam) {
      vehiclePlats = [kendaraanPlatParam];
    }

    const vehicles = vehiclePlats
      ? await prisma.kendaraan.findMany({ where: { platNomor: { in: vehiclePlats } } })
      : await prisma.kendaraan.findMany();

    // 2. Aggregate data per vehicle
    const report = await Promise.all(vehicles.map(async (v) => {
        // Income from Uang Jalan (sisa uang jalan considered profit/saving? No, usually income is from transporting goods)
        // Wait, income logic depends on business model. Assuming income comes from "Uang Jalan" given or "Nota Sawit" transport fees.
        // For now, let's assume cost center focuses on EXPENSES vs ALLOCATED BUDGET.
        // OR: Profit = (Income generated by truck) - (Uang Jalan + Service + Fuel)
        
        // Simpler approach for now:
        // Expenses: ServiceLogs, Uang Jalan (expense for company)
        
        const serviceCost = await prisma.serviceLog.aggregate({
            where: {
                kendaraanPlat: v.platNomor,
                date: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc }
            },
            _sum: { cost: true }
        });

        const uangJalan = await prisma.uangJalan.aggregate({
            where: {
                sesiUangJalan: {
                    kendaraanPlatNomor: v.platNomor
                },
                tipe: 'PENGELUARAN',
                date: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc }
            },
            _sum: { amount: true }
        });

        const kasCost = await prisma.kasTransaksi.aggregate({
            where: {
                deletedAt: null,
                tipe: 'PENGELUARAN',
                kendaraanPlatNomor: v.platNomor,
                kebunId: null,
                karyawanId: null,
                date: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc },
            },
            _sum: { jumlah: true },
        })

        const trips = kebunId
          ? await prisma.notaSawit.count({
              where: {
                kendaraanPlatNomor: v.platNomor,
                kebunId,
                createdAt: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc },
              }
            })
          : await prisma.sesiUangJalan.count({
              where: {
                  kendaraanPlatNomor: v.platNomor,
                  tanggalMulai: { gte: monthRange.startUtc, lt: monthRange.endExclusiveUtc }
              }
            });

        return {
            platNomor: v.platNomor,
            merk: v.merk,
            totalTrips: trips,
            serviceCost: serviceCost._sum.cost || 0,
            uangJalanCost: uangJalan._sum.amount || 0,
            kasCost: kasCost._sum.jumlah || 0,
            totalCost: (serviceCost._sum.cost || 0) + (uangJalan._sum.amount || 0) + (kasCost._sum.jumlah || 0)
        };
    }));

    return NextResponse.json(report);
  } catch (error) {
    console.error('Error fetching cost center report:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
