version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/public/uploads
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npm run prisma:deploy && npm run start"
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
  uploads_data:
